#!/usr/bin/env bash
# ===============================================
# PwdGen - By : 3xpl0it Sh4d0w - Copyleft : 2021.
# ===============================================
# Date de Création      : 02-07-2021.
# Date de Modification  : 21-07-2021.
# ===============================================

INTERFACE="$1"
ARGUMENT_1="$2"
ARGUMENT_2="$3"

MODULE_COLORS()
{
    RESET="\033[0m"

    RED="\033[1;31m"
    BLUE="\033[1;34m"
    CYAN="\033[1;36m"
    GREY="\033[1;30m"
    GREEN="\033[1;32m"
    WHITE="\033[1;37m"
    YELLOW="\033[1;33m"
}
MODULE_COLORS

MODULE_FORMATAGE()
{   
    TAB="\t"
    LINE_BREACK="\n"
    
    SEP=${GREY}" - "${RESET}
    START=${GREY}"[ "${RESET}
    END=${GREY}" ] ${LINE_BREACK}"${RESET}
    LINE=${GREY}"====================================================================== ${LINE_BREACK}"${RESET}

}

MODULE_BANNER()
{
    SCRIPT_NAME=${CYAN}"CLI PwdGen"${RESET}
    SCRIPT_AUTHOR=${YELLOW}"By : 3xpl0it Sh4d0w"${RESET}
    SCRIPT_VERSION=${GREEN}"Version : 1.0"${RESET}
    SCRIPT_COPYLEFT=${GREEN}"Copyleft : 2022"${RESET}

    printf "${LINE}"
    printf "${START}${CYAN}       ██████╗ ██╗    ██╗██████╗  ██████╗ ███████╗███╗   ██╗      ${RESET}${END}" 
    printf "${START}${CYAN}       ██╔══██╗██║    ██║██╔══██╗██╔════╝ ██╔════╝████╗  ██║      ${RESET}${END}" 
    printf "${START}${CYAN}       ██████╔╝██║ █╗ ██║██║  ██║██║  ███╗█████╗  ██╔██╗ ██║      ${RESET}${END}" 
    printf "${START}${CYAN}       ██╔═══╝ ██║███╗██║██║  ██║██║   ██║██╔══╝  ██║╚██╗██║      ${RESET}${END}" 
    printf "${START}${CYAN}       ██║     ╚███╔███╔╝██████╔╝╚██████╔╝███████╗██║ ╚████║      ${RESET}${END}"
    printf "${START}${CYAN}       ╚═╝      ╚══╝╚══╝ ╚═════╝  ╚═════╝ ╚══════╝╚═╝  ╚═══╝      ${RESET}${END}" 

    printf "${LINE}" 
    printf "${START}${SCRIPT_NAME}${SEP}${SCRIPT_AUTHOR}${SEP}${SCRIPT_VERSION}${SEP}${SCRIPT_COPYLEFT}${END}" 
    printf "${LINE}" 
}

PWDGEN_CLI()
{
    ARGUMENT_1="$1"
    ARGUMENT_2="$2"

    cat /dev/random | tr -dc 'a-zA-Z0-9!?@#$%^&*"^_+=><~`:;.' | fold -w $ARGUMENT_1 | head -n $ARGUMENT_2
}

PWDGEN_GUI()
{
    clear && MODULE_BANNER

    read -p "$(printf "Veuillez Choisir la Longeur dU Mot de Passe : ")" LNG_PASS

    clear && MODULE_BANNER

    read -p "$(printf "Veuillez Choisir le Nombre de Mots de Passe : ")" NBR_PASS

    GENERATE_PASSWORD=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9!?@#$%^&*"^_+=><~`:;.' | fold -w ${LNG_PASS} | head -n ${NBR_PASS})

    clear && MODULE_BANNER && GENERATE_PASSWORD
}

if [[ ("${INTERFACE}" = "CLI") ]] || \
[[ ("${INTERFACE}" = "cli") ]] || \
[[ ("${INTERFACE}" = "-C") ]] || \
[[ ("${INTERFACE}" = "-c") ]]
    then
        PWDGEN_CLI $ARGUMENT_1 $ARGUMENT_2
fi

if [[ ("${INTERFACE}" = "GUI") ]] || \
[[ ("${INTERFACE}" = "gui") ]] || \
[[ ("${INTERFACE}" = "-G") ]] || \
[[ ("${INTERFACE}" = "-g") ]]
    then
        PWDGEN_GUI
fi